In [36]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [37]:
import numpy as np

In [38]:
a=np.array([1,2,3])
print (f"a: {a}\n")
b=np.array([(1,2,3),(4,5,6)])
print(f"b: {b}\n")

a: [1 2 3]

b: [[1 2 3]
 [4 5 6]]



In [39]:
#Arreglo de 3 Dimensiones
b=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(f"b: {b}\n")

b: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



In [40]:
#Memoria que contiene estos datos del arreglo
x=np.array([1,2,3,4])
x.data

In [41]:
x=range(6)
for n in x:
    print(n)

0
1
2
3
4
5


In [42]:
#Calcula y muestra el tamaño en bytes de la lista y este se multiplica por la longitud de la lista
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))
#Calcula y muestra el tamaño en bytes del arreglo y este se multiplica por estos valores que dan el tamaño total


D=np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [43]:
#Compara el rendimiento de formas de realizar operaciones en listas o arrays.
import time

SIZE=1000000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=[(x,y)for x,y in zip(L1,L2)] #Revisar Comprehension
print((time.time()-start)*1000)

start=time.time()
result=A1+A2
print((time.time()-start)*1000)

375.31208992004395
133.80026817321777


In [44]:
import time
import numpy as np
#Se calcula el tiempo transcurrido desde el tiempo transcurrido hasta 5 decimales.
list1=[i for i in range(10000)]
list2=[i for i in range(10000)]

inicio=time.time()
dot=0
for i,j in zip (list1,list2):
    dot0=i*j
round(time.time()-inicio,5)

0.00362

In [45]:
import time
import numpy as np
#Se calcula el tiempo transcurrido desde el tiempo transcurrido hasta 5 decimales.
arr1=np.array([i for i in range(10000)])
arr2=np.array([i for i in range(10000)])

inicio=time.time()
arr=np.dot(arr1,arr2)

round(time.time()-inicio,5)

0.0

In [46]:
#Concatenacion de dos arreglos
#Forma1
arr1=np.array([i for i in range(100000)])
arr2=np.array([i for i in range(100000)])

inicio=time.time()
list1+=list2
round(time.time()-inicio,5)

0.0

In [47]:
#Forma2
arr1=np.array([i for i in range(100000)])
arr2=np.array([i for i in range(100000)])

inicio=time.time()
arr=np.concatenate((arr1,arr2),axis=0)
round(time.time()-inicio,5)


0.0

In [53]:
#Eliminacion
#Forma1
import time
import numpy as np
list1=[1 for i in range(100000)]
inicio=time.time()
del(list1)
round(time.time()-inicio,5)

0.0

In [52]:
#Forma2
import time
import numpy as np
arr1=np.array([i for i in range(100000)])
inicio=time.time()
del(arr1)
round(time.time()-inicio,5)

0.0

In [59]:
#Lista
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)

print(vector[3])
#Multiplicar x5 cada elemento
print(vector*5)
#Sumar los elementos
print(np.sum(vector))
#Promedio media de los elementos
print(np.mean(vector))
#Sumar su propio vector
print(vector+vector)

[25.  12.  15.  66.  12.5]
66.0
[125.   60.   75.  330.   62.5]
130.5
26.1
[ 50.  24.  30. 132.  25.]


In [67]:
#MATRICES
lista=[[1,-4],[12,3],[7.2,5]]
matriz=np.array(lista)
print(f"{matriz}\n")

#Matriz creada con np.zeros
dimensiones=(2,3)
matrizCeros=np.zeros(dimensiones)
print(f"{matrizCeros}\n")

#Matriz creada con np.ones
dimensiones=(3,2)
matrizUnos=np.ones(dimensiones)
print(f"{matrizUnos}\n")

#Compia de matriz creada connp.Ones
matrizCopia=np.copy(matrizUnos)
print(f"{matrizCopia}\n")

[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]



In [78]:
#EJERCICIOS PARA REALIZAR
# 1.- Crear matriz 4x4 con valores 0.5
#Compia de matriz creada connp.Ones
dimensiones=(4,4)
matriz05=(np.ones(dimensiones))/2
print(f"{matriz05}\n")

#Crear Matriz 5x5 con valores al azar de 1 al 101
import random
dimensiones=(5,5)
matrizRandom=np.random.randint(1,101,dimensiones)
print(f"{matrizRandom}\n")

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

[[79 49 51 25 19]
 [89 22 11 58 75]
 [12 46  5 25 65]
 [88 12  2 49 70]
 [91 57 52 75 12]]



In [79]:
#Otros Ejercicios
#Crear un Vector con Valores dentro del rango 10 a 49
a=np.arange(10,50)
print(f"{a}\n")
#Invertir el vector a[::-1]
aInvertido=a[::-1]
print(f"{aInvertido}\n")
#Crea una matriz identidad de 6x6
matrizIdentidad=np.identity(6)
print(f"{matrizIdentidad}\n")
#Crea una matriz con valores al azar con forma 3x3
r=np.random.random((3,3,3))
print(f"{r}\n")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[[0.93308532 0.95522486 0.18346343]
  [0.8566423  0.25032029 0.18877242]
  [0.27835503 0.31546253 0.0599946 ]]

 [[0.40078029 0.92245943 0.84354693]
  [0.69517469 0.39788069 0.29572227]
  [0.35723741 0.32313696 0.51083501]]

 [[0.68808213 0.65023523 0.17246824]
  [0.17127924 0.02893676 0.32545972]
  [0.72620645 0.61493186 0.18648916]]]



In [82]:
#Encontrar los indices de los valores minimos y maximos de la anterior matriz
print(r.argmax())
print(r.ravel()[r.argmax()])

print(r)
print(np.unravel_index(r.argmax(),r.shape))
r[np.unravel_index(r.argmax(),r.shape)]

#Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior 
z=np.ones((10,10))

z[1:-1,1:-1]=0
print(z)

1
0.9552248582196053
[[[0.93308532 0.95522486 0.18346343]
  [0.8566423  0.25032029 0.18877242]
  [0.27835503 0.31546253 0.0599946 ]]

 [[0.40078029 0.92245943 0.84354693]
  [0.69517469 0.39788069 0.29572227]
  [0.35723741 0.32313696 0.51083501]]

 [[0.68808213 0.65023523 0.17246824]
  [0.17127924 0.02893676 0.32545972]
  [0.72620645 0.61493186 0.18648916]]]
(0, 0, 1)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [88]:
#Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4 
matriz5x5=np.tile(np.arange(0,5),5).reshape(5,5)
print(matriz5x5)
#Crear dos arreglos al azar A y B, verificar si son iguales
a=np.random.random((3,3))
b=np.random.random((3,3))
a==b

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [101]:
#Tomar el tiempo de multiplicacion de matrices de las siguientes dimensiones: 10x10,100x100,1000x1000
#Guardar los tiempos de resultados en un archivo
dimensiones=[(10,10),(100,100),(1000,1000)]
tiempos=[]

for dims in dimensiones:
    matrizA=np.random.rand(*dims)
    matrizB=np.random.rand(*dims)

    inicio=time.time()
    resultado=np.dot(matrizA,matrizB)
    tiempoTranscurrido=time.time()-inicio

    tiempos.append(tiempoTranscurrido)
#Guardar arreglos en archivo
np.save("tiemposMultiplicacion.npy",tiempos)

# Guardar un arreglo en un archivo .npy y cargarlo
arr=np.arange(10)
np.save('archivo.npy',arr)
loaded_arr=np.load('archivo.npy')

# Guardar múltiples arreglos en un archivo .npz y cargarlo
np.savez("array_archive.npz",a=arr,b=arr)
arch=np.load("array_archive.npz")
loaded_b=arch["b"]

In [104]:
#Archivos csv
#Para guardar el archive en formato csv y con un delimitador ","
np.savetxt("archivo.csv",arr,delimiter=",")

#Extraer el arreglo
arr2=np.loadtxt("archivo.csv",delimiter=",")