In [5]:
#Ejercicio 26
import numpy as np
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

C:\Users\User\AppData\Local\Temp\ipykernel_15988\3197292124.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\User\AppData\Local\Temp\ipykernel_15988\3197292124.py:4: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)
C:\Users\User\AppData\Local\Temp\ipykernel_15988\3197292124.py:5: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\User\AppData\Local\Temp\ipykernel_15988\3197292124.py:6: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0.)


nan

In [30]:
#Ejercicio 27
Z = np.random.uniform(-10, +10, 10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[ 4. -4.  6.  6.  1.  4.  5. -3. 10. -5.]


In [1]:
#Ejercicio 28


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [2]:
#Ejercicio 29
import numpy as np
row_values = np.arange(5)
matrix_5x5 = np.tile(row_values, (5, 1))
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
#Ejercicio 30
import numpy as np
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
#Ejercicio 31
import numpy as np
Z = np.linspace(0.0001, 0.9999, 10)
print(Z)


[1.00000000e-04 1.11188889e-01 2.22277778e-01 3.33366667e-01
 4.44455556e-01 5.55544444e-01 6.66633333e-01 7.77722222e-01
 8.88811111e-01 9.99900000e-01]


In [6]:
#Ejercicio 32
Z = np.random.random(10)
Z.sort()
print(Z)


[0.02788519 0.11737276 0.37710036 0.44937175 0.58284329 0.72906425
 0.73169935 0.79959264 0.86333616 0.89070398]


In [9]:
#Ejercicio 33
Z = np.arange(10)
result = np.add.reduce(Z)
print(f"{result}\n")
#or
result=sum(Z)

45



In [10]:
#Ejercicio 34
# Generate two random arrays A and B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.array_equal(A, B)
print(equal)

False


In [12]:
#Ejercicio 35
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False

In [13]:
#Ejercicio 36
import numpy as np
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)

print(R)
print(T)


[0.77818957 0.99967459 0.58060408 0.82539806 1.02480986 0.99391207
 0.96796015 0.65664449 0.97457552 0.88493744]
[0.01899395 0.95945183 0.79868921 1.55633747 0.89947128 1.29788468
 1.42346386 1.27387009 1.28582095 0.88604643]


In [14]:
#Ejercicio 37
import numpy as np

# Genera un vector random de tamanio 10
Z = np.random.random(10)

# remplaza el max valor con 0
Z[Z.argmax()] = 0

print(Z)


[0.33830508 0.46375173 0.         0.62730267 0.06744423 0.69040358
 0.63423632 0.42801205 0.18483742 0.80760691]


In [15]:
#Ejercicio 38
import numpy as np

# Create una estructura array con x y y
Z = np.zeros((10, 10), dtype=[('x', float), ('y', float)])
#Genera coordenadas
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 10),
                              np.linspace(0, 1, 10))

print(Z)


[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [18]:
#Ejercicio 39
import numpy as np
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
determinant = np.linalg.det(C)

print(determinant)

3638.1636371179666


In [23]:
#Ejercicio 40
import numpy as np

# Tipos
for dtype in [np.int8, np.int32, np.int64]:
    print("Minimum representable value for {}: {}".format(dtype, np.iinfo(dtype).min))
    print("Maximum representable value for {}: {}".format(dtype, np.iinfo(dtype).max))

for dtype in [np.float32, np.float64]:
    print("Minimum representable value for {}: {}".format(dtype, np.finfo(dtype).min))
    print("Maximum representable value for {}: {}".format(dtype, np.finfo(dtype).max))
    print("Smallest positive representable number for {}: {}".format(dtype, np.finfo(dtype).eps))

Minimum representable value for <class 'numpy.int8'>: -128
Maximum representable value for <class 'numpy.int8'>: 127
Minimum representable value for <class 'numpy.int32'>: -2147483648
Maximum representable value for <class 'numpy.int32'>: 2147483647
Minimum representable value for <class 'numpy.int64'>: -9223372036854775808
Maximum representable value for <class 'numpy.int64'>: 9223372036854775807
Minimum representable value for <class 'numpy.float32'>: -3.4028234663852886e+38
Maximum representable value for <class 'numpy.float32'>: 3.4028234663852886e+38
Smallest positive representable number for <class 'numpy.float32'>: 1.1920928955078125e-07
Minimum representable value for <class 'numpy.float64'>: -1.7976931348623157e+308
Maximum representable value for <class 'numpy.float64'>: 1.7976931348623157e+308
Smallest positive representable number for <class 'numpy.float64'>: 2.220446049250313e-16


In [24]:
#Ejercicio 41
import numpy as np
np.set_printoptions(threshold=np.inf)

Z = np.zeros((25, 25))

print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [26]:
#Ejercicio 42
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()

print(Z[index])

68


In [28]:
#Ejercicio 43
import numpy as np

# Create a structured array with 10 elements
Z = np.zeros(10, dtype=[('position', [('x', float, (1,)), ('y', float, (1,))]),
                        ('color', [('r', float, (1,)), ('g', float, (1,)), ('b', float, (1,))])])

print(Z)


[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


In [31]:
#Ejercicio 44
import numpy as np
Z = np.random.random((100, 2))
X, Y = np.atleast_2d(Z[:, 0]), np.atleast_2d(Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

#OTRO
import scipy.spatial
Z = np.random.random((100, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[0.         0.36244455 0.60025199 0.36255393 0.31401963 0.36156692
  0.50448289 0.58409091 0.2679772  0.40999149 0.63100825 0.57145607
  0.2337844  0.72041796 0.56572274 0.4909908  0.72334295 0.20079571
  0.51933583 0.50923222 0.24935257 0.0229449  0.62244054 0.52346312
  0.29307177 0.27518599 0.48239012 0.3691713  0.42775545 0.39412409
  0.77907988 0.16889281 0.13691059 0.61210153 0.61864071 0.28417111
  0.75190747 0.52570895 0.60019861 0.30276014 0.33915377 0.26125811
  0.26248967 0.078459   0.63817477 0.6673874  0.21862124 0.35094577
  0.55897751 0.25705456 0.22688739 0.19697712 0.49585274 0.17477471
  0.37901769 0.08594814 0.39867272 0.15325728 0.13930744 0.48482525
  0.49374967 0.26173183 0.09808937 0.15745285 0.65373376 0.5862934
  0.30287118 0.54022355 0.34724996 0.36743596 0.65046013 0.70772748
  0.56103598 0.42008027 0.32488113 0.63578152 0.27409272 0.18837466
  0.23485331 0.38297013 0.48588605 0.37030631 0.09876344 0.21990461
  0.20947943 0.19520567 0.5239137  0.24486121 0.5

ModuleNotFoundError: No module named 'scipy'

In [33]:
#Ejercicio 45
import numpy as np
Z = np.arange(10, dtype=np.float32)

Z = Z.view(np.int32)

print(Z)


[         0 1065353216 1073741824 1077936128 1082130432 1084227584
 1086324736 1088421888 1090519040 1091567616]


In [34]:
#Ejercicio 46
import numpy as np
Z = np.genfromtxt("missing.dat", delimiter=",")

print(Z)

FileNotFoundError: missing.dat not found.

In [35]:
#Ejercicio 47
import numpy as np
Z = np.arange(9).reshape(3,3)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [36]:
#Ejercicio 48
import numpy as np
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0

G = np.exp(-((D - mu)**2) / (2.0 * sigma**2))

print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [37]:
#Ejercicio 49
import numpy as np

n = 10  
p = 3   
Z = np.zeros((n, n)) 

indices = np.random.choice(range(n * n), p, replace=False)
np.put(Z, indices, 1)

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
#Ejercicio 50
import numpy as np

X = np.random.rand(5, 10)  
Y_recent = X - X.mean(axis=1, keepdims=True)

Y_old = X - X.mean(axis=1).reshape(-1, 1)

print("V. Reciente de numpy:")
print(Y_recent)
print("\nVersion antigua de numpy:")
print(Y_old)


V. Reciente de numpy:
[[ 0.47009127 -0.15200425 -0.37653632 -0.18847845 -0.14123976 -0.29485842
  -0.01062275  0.3946717  -0.18290642  0.4818834 ]
 [ 0.16127212  0.25347248 -0.38840882 -0.38641174  0.4275003  -0.24214005
  -0.19778338  0.4101451   0.32896634 -0.36661235]
 [ 0.293735   -0.3355937   0.26144156 -0.5291425   0.12733193  0.34407668
  -0.60639359  0.07201495  0.34600687  0.02652281]
 [ 0.34906689 -0.10281114 -0.41092212  0.37902491  0.20204684 -0.07065984
  -0.37496249  0.15830235 -0.40714592  0.27806052]
 [-0.33127767 -0.19458595  0.41383674 -0.12803353 -0.18720766 -0.23858406
   0.29189905 -0.25394475  0.33921794  0.2886799 ]]

Version antigua de numpy:
[[ 0.47009127 -0.15200425 -0.37653632 -0.18847845 -0.14123976 -0.29485842
  -0.01062275  0.3946717  -0.18290642  0.4818834 ]
 [ 0.16127212  0.25347248 -0.38840882 -0.38641174  0.4275003  -0.24214005
  -0.19778338  0.4101451   0.32896634 -0.36661235]
 [ 0.293735   -0.3355937   0.26144156 -0.5291425   0.12733193  0.34407668
 